trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-get update && sudo apt-get install -y terraform
  displayName: Install Terraform

- script: terraform version
  displayName: Check Terraform Version

- script: terraform init
  displayName: Terraform Init

- script: terraform plan
  displayName: Terraform Plan