trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: terraform version
  displayName: Check Terraform Version

- script: terraform init
  displayName: Terraform Init

- script: terraform plan
  displayName: Terraform Plan

- task: AzureCLI@2
  inputs:
    azureSubscription: 'terraform-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      terraform init
      terraform plan